language: java
jdk:
- oraclejdk8

script:
- ./gradlew test

before_deploy:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
- echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get update
- sudo apt-get install cf-cli

deploy:
  provider: script
  script: ./gradlew deploy
  on:
    branch: dev
